openapi: 3.0.1
info:
  title: Conversion API
  description: An API that converts video, audio, and file formats to other formats.
  version: '0.2'
servers:
  - url: http://localhost
paths:
  /WebServicesProject/Converter/api/client/name:
    put:
      description: Updates client name
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
            examples:
              '0':
                value: |-
                  [
                      {
                          "licenseNumber": {licenseNumber},
                          "clientName": "{new client name}"
                      }
                  ]
      responses:
        '200':
          description: Name Updated.
          content:
            text/html; charset=UTF-8:
              schema:
                type: string
              examples: {}
      servers:
        - url: http://localhost
    servers:
      - url: http://localhost
  /WebServicesProject/Converter/api/client/{licenseNumber}:
    get:
      description: Gets all the conversions made by a client
      responses:
        '200':
          description: Returns the JSON data from all conversions by the client
          content:
            text/html; charset=UTF-8:
              schema:
                type: string
              examples: {}
      servers:
        - url: http://localhost
    delete:
      description: Deletes a client based on their license number
      responses:
        '200':
          description: Client successfully deleted
          content:
            text/html; charset=UTF-8:
              schema:
                type: string
              examples: {}
      servers:
        - url: http://localhost
    head:
      description: Displays the response header of the given resource
      responses:
        '200':
          description: Displays the response header of the given resource
      servers:
        - url: http://localhost
    servers:
      - url: http://localhost
  /WebServicesProject/Converter/api/video/{licenseNumber}:
    get:
      description: Gets all the video conversions from the client with the license number
      responses:
        '200':
          description: Displays the JSON data of all the video conversions made by the client
          content:
            text/html; charset=UTF-8:
              schema:
                type: string
              examples: {}
      servers:
        - url: http://localhost
    servers:
      - url: http://localhost
  /WebServicesProject/Converter/api/file/{licenseNumber}:
    get:
      description: Gets all the file conversions from the client with the license number
      responses:
        '200':
          description: Displays the JSON data of all the file conversions made by the client
          content:
            text/html; charset=UTF-8:
              schema:
                type: string
              examples: {}
      servers:
        - url: http://localhost
    servers:
      - url: http://localhost
  /WebServicesProject/Converter/api/file/convert:
    post:
      description: Converts an input file format into a chosen format
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
            examples:
              '0':
                value: |-
                  [
                      {
                          "licenseNumber": {licenseNumber},
                          "password_hash": "{password}",
                          "originalFormat": "{originalFormat}",
                          "targetFormat": "{targetFormat}",
                          "file": "{Input file path}"
                      }
                  ]
      responses:
        '200':
          description: File successfully converted
          content:
            text/html; charset=UTF-8:
              schema:
                type: string
              examples: {}
      servers:
        - url: http://localhost
    servers:
      - url: http://localhost
  /WebServicesProject/Converter/api/client/create:
    post:
      description: Creates a client with a client name and password
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
            examples:
              '0':
                value: |-
                  [
                      {
                          "clientName": "{name of the client}",
                          "password_hash": "{password}"
                      }
                  ]
      responses:
        '200':
          description: Client successfully created
          content:
            text/html; charset=UTF-8:
              schema:
                type: string
              examples: {}
      servers:
        - url: http://localhost
    servers:
      - url: http://localhost
  /WebServicesProject/Converter/api/video/convert:
    post:
      description: Converts an input video or audio format into a chosen format
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
            examples:
              '0':
                value: |-
                  [
                      {
                          "licenseNumber": {licenseNumber},
                          "password_hash": "{password}",
                          "originalFormat": "{originalFormat}",
                          "targetFormat": "{targetFormat}",
                          "file": "{Input file path}"
                      }
                  ]
      responses:
        '200':
          description: Video successfully converted
          content:
            text/html; charset=UTF-8:
              schema:
                type: string
              examples: {}
      servers:
        - url: http://localhost
    servers:
      - url: http://localhost
  /WebServicesProject/Converter/api/file/{conversionID}:
    delete:
      description: Deletes a file with the conversion id parameter
      responses:
        '200':
          description: File successfully deleted
          content:
            text/html; charset=UTF-8:
              schema:
                type: string
              examples: {}
      servers:
        - url: http://localhost
    servers:
      - url: http://localhost
  /WebServicesProject/Converter/api/video/{conversionID}:
    delete:
      description: Deletes a video or audio with the conversion id parameter
      responses:
        '200':
          description: Video successfully deleted
          content:
            text/html; charset=UTF-8:
              schema:
                type: string
              examples: {}
      servers:
        - url: http://localhost
    servers:
      - url: http://localhost
  /WebServicesProject/Converter/api/client/password:
    put:
      description: Changes the password of a client with a certain license number
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
            examples:
              '0':
                value: |-
                  [
                      {
                          "licenseNumber": {licenseNumber},
                          "password_hash": "{password}"
                      }
                  ]
      responses:
        '200':
          description: Password Updated.
          content:
            text/html; charset=UTF-8:
              schema:
                type: string
              examples: {}
      servers:
        - url: http://localhost
    servers:
      - url: http://localhost